FROM python:3.12-slim

WORKDIR /app

COPY mcp/sql_generator/requirements.txt .
# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8005

# Копирование будет через volumes, поэтому здесь не копируем код

CMD ["python", "mcp_sql_gen.py"]