FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY mcp/rag_bikes/requirements.txt .
# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8007
# Копирование будет через volumes, поэтому здесь не копируем код

CMD ["python", "mcp_rag_bikes.py"]